[package]
org = "ballerina"
name = "graphql"
version = "@toml.version@"
authors = ["Ballerina"]
export=["graphql", "graphql.subgraph", "graphql.dataloader"]
keywords = ["gql", "network", "query", "service"]
repository = "https://github.com/ballerina-platform/module-ballerina-graphql"
icon = "icon.png"
license = ["Apache-2.0"]
distribution = "2201.5.0"

[[platform.java11.dependency]]
groupId = "io.ballerina.stdlib"
artifactId = "graphql-native"
version = "@toml.version@"
path = "../native/build/libs/graphql-native-@project.version@.jar"

[[platform.java11.dependency]]
groupId = "io.ballerina.stdlib"
artifactId = "graphql-compiler-plugin"
version = "@toml.version@"
path = "../commons/build/libs/graphql-commons-@project.version@.jar"
