[plugin]
id = "sabtharm-compiler-plugin"
class = "io.sabtharm.stdlib.graphql.compiler.GraphqlCompilerPlugin"

[[dependency]]
path = "../compiler-plugin/build/libs/sabtharm-compiler-plugin-@project.version@.jar"

[[dependency]]
path = "../commons/build/libs/sabtharm-commons-@project.version@.jar"
