[package]
org = "sabtharm"
name = "graphql"
version = "1.13.2"
authors = ["Ballerina"]
export=["graphql", "graphql.subgraph", "graphql.dataloader"]
keywords = ["gql", "network", "query", "service"]
repository = "https://github.com/ballerina-platform/module-ballerina-graphql"
icon = "icon.png"
license = ["Apache-2.0"]
distribution = "2201.9.0"

[platform.java17]
graalvmCompatible = true

[[platform.java17.dependency]]
groupId = "io.ballerina.stdlib"
artifactId = "graphql-native"
version = "1.13.2"
path = "../native/build/libs/graphql-native-1.13.2-SNAPSHOT.jar"

[[platform.java17.dependency]]
groupId = "io.ballerina.stdlib"
artifactId = "sabtharm-commons"
version = "1.13.2"
path = "../commons/build/libs/sabtharm-commons-1.13.2-SNAPSHOT.jar"
