[plugin]
id = "sabtharm-compiler-plugin"
class = "io.sabtharm.stdlib.graphql.compiler.GraphqlCompilerPlugin"

[[dependency]]
path = "../compiler-plugin/build/libs/sabtharm-compiler-plugin-1.13.2-SNAPSHOT.jar"

[[dependency]]
path = "../commons/build/libs/sabtharm-commons-1.13.2-SNAPSHOT.jar"
