name: Publish Release

on:
    workflow_dispatch:
    repository_dispatch:
        types: [ stdlib-release-pipeline ]

jobs:
    call_workflow:
        name: Run Release Workflow
        if: ${{ github.repository_owner == 'ballerina-platform' }}
        uses: ballerina-platform/ballerina-standard-library/.github/workflows/release-package-template.yml@main
        with:
            package-name: graphql
            package-org: ballerina
            additional-build-flags: '-x :graphql-examples:build'
            ballerina-bot-username: ${{ secrets.BALLERINA_BOT_USERNAME }}
            ballerina-bot-email: ${{ secrets.BALLERINA_BOT_EMAIL }}
            ballerina-bot-token: ${{ secrets.BALLERINA_BOT_TOKEN }}
            ballerina-central-access-token: ${{ secrets.BALLERINA_CENTRAL_ACCESS_TOKEN }}
